# Generated by Django 3.1 on 2020-09-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment_foo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='foo2',
        ),
    ]
